# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 2) do

  create_table "license_plates", :force => true do |t|
    t.column "state",     :string
    t.column "number",    :string
    t.column "issued_on", :date
    t.column "color",     :string
    t.column "extra",     :string
  end

  create_table "people", :force => true do |t|
    t.column "type",                     :string
    t.column "name",                     :string
    t.column "social_security_number",   :string
    t.column "birthdate",                :date
    t.column "became_important_on",      :date
    t.column "first_speeding_ticket_at", :datetime
  end

end
